### PR TITLE
Update mentors

### PR DESCRIPTION
**Pull request by roman-r-m**
* Remove Caleb and tessus from mentors
* Remove myself from some projects
* Add myself for standalone sync API

### CODE REVIEW

**Comment by laurent22** [comment]
Tessus will be a mentor actually (he's just not very active on Discord)

**Comment by roman-r-m** [comment]
Ah, good. I'll keep his name then.

Just wanted to prevent people from being harassed needlessly.

**Comment by roman-r-m** [comment]
Ok, done.

**Comment by laurent22** [comment]
<s>Sure, I'm going to remove all mentors then since we don't need this information for now.</s>

(sorry I didn't realise that it was a pull request and it was already done)

**Comment by laurent22** [comment]
Thanks for updating this!

**Comment by tessus** [comment]
> (he's just not very active on Discord)

Yep, I am trying to change that during GSoC.

**Pull request merged**
